2018-04-20 17:10:57,788 14757-123145338400768 ERROR: Failed when saving price [in /Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py:64]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 52, in priceNew
    post.save()
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/mongosupport/mongosupport.py", line 855, in save
    if not self.validate():
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/mongosupport/mongosupport.py", line 483, in validate
    self._validate_required(self)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/mongosupport/mongosupport.py", line 548, in _validate_required
    self._raise_exception(DataError, rf, "%s is required" % rf)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/mongosupport/mongosupport.py", line 572, in _raise_exception
    raise exception(message)
DataError: uid is required
2018-04-21 13:41:07,646 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 13:51:07,673 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 14:01:08,677 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 14:11:07,674 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 14:21:07,675 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 15:02:06,710 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 15:11:06,714 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 15:21:06,716 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 15:35:06,724 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 15:51:28,722 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:01:06,731 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:11:06,723 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:21:06,726 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:31:06,721 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:41:06,726 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 16:52:06,726 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:07:56,727 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:13:06,731 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:21:06,723 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:31:06,736 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:46:57,731 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 17:57:06,722 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 18:11:09,740 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 18:23:09,761 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 18:36:08,728 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 18:52:34,626 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 19:01:08,656 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 19:17:04,644 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 19:30:07,663 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 19:41:08,168 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 19:57:33,695 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 20:11:06,675 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 20:26:06,685 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 20:35:06,696 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 20:49:05,687 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 21:05:31,740 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 21:20:05,681 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 21:36:01,687 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 21:52:27,680 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 22:01:04,653 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 22:14:04,614 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 22:29:03,704 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 22:42:03,644 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 22:51:03,658 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 23:01:03,678 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 23:17:00,750 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 23:31:03,604 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-21 23:51:55,755 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
